rabbitmq:
  image: rf37535/rabbitmq

controlengine:
  image: rf37535/robocode:controlengine
  links:
    - rabbitmq

gp:
  image: rf37535/build
  links:
    - rabbitmq

pso:
  image: rf37535/build
  links:
    - rabbitmq
