rabbitmq:
  image: rf37535/rabbitmq
  ports:
  - 5672:5672

build:
  command: bash -c "cd /source && make"
  image: rf37535/build
  volumes:
  - ~/Workspace/Github/GeneticProgrammingRobocode/:/source

clean:
  command: bash -c "cd /source && make clean"
  image: rf37535/build
  volumes:
  - ~/Workspace/Github/GeneticProgrammingRobocode/:/source
